/*
 * This source file was generated by the Gradle 'init' task
 */
package goitpackage;

import com.google.gson.Gson;

public class App {

    public static void main(String[] args) {
        System.out.println(new Gson().toJson(new User("Tychon", "Vilkhovyi")));
    }

    public static class User {
        String name;
        String lastName;

        public User(String name, String lastName) {
            this.name = name;
            this.lastName = lastName;
        }
    }

}